theme: minima
title: leos RC Aircraft Photography
author: Lio
description: I post the photos I take at various RC aviation events. Enjoy!
links:
YouTube:
https://www.youtube.com/@leozengy/featured
Discord
https://discord.gg/JZe2VK5UWB
Facebook: 
https://www.facebook.com/zeng.leo2011/
Instagram:
https://www.instagram.com/zeng.lio/
Grabcad:
https://grabcad.com/leo.zeng-5/models?fbclid=IwY2xjawQ0uFNleHRuA2FlbQIxMQBzcnRjBmFwcF9pZAEwAAEeovoc-lnVvRyxGqtlVr7VBmt5leiLLaZhmqQlA5xWy4wMX-G8tF60t4yTsKA_aem_Z0j0opeJ2j2EkosoguGHRw
